"""empty message

Revision ID: 3eb477bf244d
Revises: None
Create Date: 2014-11-02 13:47:21.783506

"""

# revision identifiers, used by Alembic.
revision = '3eb477bf244d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
